(define-lw-system :lw-basic ()
  (:system "lw-crypto")
  (:system "lw-date")
  (:system "lw-json")
  (:system "lw-string")
  (:file "basic" :depends-on "keymap")
  (:file "forth" :depends-on "basic")
  (:file "func" :depends-on "forth")
  (:file "keymap" :depends-on "package")
  (:file "package"))
